Дан следующий код, исправьте его там, где требуется

public static void main(String[] args) throws Exception {
   try {
       int a = 90;
       int b = 3;
       System.out.println(a / b);
       printSum(23, 234);
       int[] abc = { 1, 2 };
       abc[3] = 9;
   } catch (Throwable ex) {
       System.out.println("Что-то пошло не так...");
   } catch (NullPointerException ex) {
       System.out.println("Указатель не может указывать на null!");
   } catch (IndexOutOfBoundsException ex) {
       System.out.println("Массив выходит за пределы своего размера!");
   }
}
public static void printSum(Integer a, Integer b) throws FileNotFoundException {
   System.out.println(a + b);
}

1. Исключение Throwable перехватывает все остальные случаи. Нужно убрать либо его, либо все другие.
2. Исключение FileNotFoundException никогда не генерируется в методе printSum.
3. Исключение NullPointerException также не возникает в данной программе, его можно убрать.
4. Попытка присвоить значение элементу с индексом 3 в массиве из двух элементов обрабатывается IndexOutOfBoundsException (Unchecked ошибка).
5. throws Exception в самом начале также не нужен.

Исправленный код (пример):
    public static void main(String[] args) {
        try {
            int a = 90;
            int b = 3;
            System.out.println(a / b);
            printSum(23, 234);
            int[] abc = { 1, 2 };
            abc[3] = 9;
        } catch (IndexOutOfBoundsException ex) {
            System.out.println("Массив выходит за пределы своего размера!");
        }
    }
    public static void printSum(Integer a, Integer b) {
        System.out.println(a + b);
    }
